### ISSUE TITLE
For HacktobeFest

### ISSUE THREAD

**Issue by sachith-1** [sachith-1/ComSOC-UWU#1]
Existing Gallery not correctly fit to device width (for desktop)

**Comment by sachith-1** [comment]
#

**Comment by eriksape** [comment]
what do you expect to see? please more detail.

**Comment by sachith-1** [comment]
you have fork and to repo and edit the index.html file to and correct the gallery width to fit with device width

**Comment by liquorburn** [comment]
I can take this

**Comment by liquorburn** [comment]
The `jquery.hislide.js` plugin is setting fixed image dimensions and therefore you need another, responsive plugin to accomplish your goal. I'm out.
